[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mpvremote"
version = "0.0.1"
dependencies = [
    "pyserial"
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[project.scripts]
mpvremote = "mpvremote.controller:main"
